### Numpy Basics

In [17]:
import numpy as np

In [18]:
myArray = np.array([1, 2, 4, 3])

In [20]:
myArray[1]

2

In [7]:
myArray.dtype

dtype('int32')

### Array Creation

In [28]:
listArr = np.array([[1, 2, 3, 4], [2, 2, 2, 5]])
listArr

array([[1, 2, 3, 4],
       [2, 2, 2, 5]])

In [25]:
listArr.shape

(2, 4)

In [26]:
listArr.size

8

In [27]:
np.array({22, 33, 44})

array({33, 44, 22}, dtype=object)

In [31]:
zeros = np.zeros(4)
zeros

array([0., 0., 0., 0.])

In [36]:
zeros.dtype

dtype('float64')

In [37]:
zeros.shape

(4,)

In [39]:
info = np.arange(15)
info

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
lspace = np.linspace(1, 10, 4)

In [45]:
lspace

array([ 1.,  4.,  7., 10.])

In [49]:
emptyArr = np.empty((2,2))
emptyArr

array([[ 1.,  4.],
       [ 7., 10.]])

In [51]:
info = np.arange(99)
info

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [53]:
info.reshape((3, 33))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [54]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 0]]

In [55]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [56]:
ar.sum(axis = 0)

array([12, 15,  9])

In [57]:
ar.sum(axis = 1)

array([ 6, 15, 15])

In [58]:
arr = np.array([1, 24, 655, 3])

In [59]:
arr

array([  1,  24, 655,   3])

In [61]:
arr.argmin()

0

In [62]:
arr.argmax()

2

In [63]:
arr.argsort()

array([0, 3, 1, 2], dtype=int64)

### Matrix Operations

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [65]:
ar2 = np.array([[1, 2, 1], [1, 2, 1], [1, 2, 1]])
ar2

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [66]:
ar + ar2

array([[ 2,  4,  4],
       [ 5,  7,  7],
       [ 8, 10,  1]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 0.        ]])

In [72]:
ar.sum()


36

In [73]:
ar.min()

0

In [74]:
ar.max()

8

In [77]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))