In [1]:
import numpy as np

In [2]:
list = [1, 2, 3, 4, 5]
print(list)

[1, 2, 3, 4, 5]


In [4]:
print('1D Array')
a = np.array([1, 2, 3, 4, 5])
print(a)

1D Array
[1 2 3 4 5]


In [5]:
print('2D Array')
a = np.array([[1, 2, 3, 4, 5],[5, 3, 4, 2, 1]])
print(a)

2D Array
[[1 2 3 4 5]
 [5 3 4 2 1]]


In [7]:
type(a)

numpy.ndarray

In [11]:
print(a.shape)

(2, 5)


In [14]:
a = np.array([[1, 2, 3, 4, 5],[5, 3, 4, 2, 1], [6, 4, 3, 2, 1]])
print(a)

[[1 2 3 4 5]
 [5 3 4 2 1]
 [6 4 3 2 1]]


In [15]:
a.transpose()

array([[1, 5, 6],
       [2, 3, 4],
       [3, 4, 3],
       [4, 2, 2],
       [5, 1, 1]])

In [16]:
############################# Functions ##########################

In [18]:
np.empty((4, 4), dtype=float)

array([[4.67296746e-307, 1.69121096e-306, 1.95820760e-306,
        8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307],
       [7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
        8.34454050e-308],
       [1.11261027e-306, 1.15706896e-306, 1.33512173e-306,
        1.33504432e-306]])

In [20]:
a = np.ones(6)
print(a)

[1. 1. 1. 1. 1. 1.]


In [27]:
a = np.ones((3, 5), dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
a = np.zeros((4, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
a = np.zeros((4, 4), dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
a = np.arange(1, 20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [39]:
a = np.arange(1, 19, 2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [40]:
a = a.reshape((3, 3))
a

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [42]:
a = a.flatten()
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [44]:
a = a.ravel()
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [45]:
## ravel -> reference of original array, flatten -> copy of original array

In [46]:
################################### ARRAY SLICING ##################################

In [47]:
a = np.arange(1, 51)
a = a.reshape(10, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [48]:
a[0]

array([1, 2, 3, 4, 5])

In [49]:
a[2]

array([11, 12, 13, 14, 15])

In [50]:
a[0, 1]

2

In [51]:
a[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
a[:5]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [53]:
a[2:5, 4]

array([15, 20, 25])

In [54]:
##################### Mathmethical Operation ########################

In [58]:
a = np.arange(0, 18).reshape((6, 3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [59]:
b = np.arange(20, 38).reshape((6, 3))
b

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [60]:
a + b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [62]:
b - a

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [65]:
print(a.shape)
print(b.shape)

(6, 3)
(6, 3)


In [68]:
b = b.reshape((3, 6))
print(a.shape)
print(b.shape)

(6, 3)
(3, 6)


In [69]:
a@b

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [70]:
b.max()

37

In [71]:
b.min()

20

In [72]:
np.sum(b)

513

In [73]:
np.mean(b)

28.5

In [74]:
np.std(b)

5.188127472091127

In [75]:
############################### Random Operations ########################

In [81]:
np.random.random(1)

array([0.06071306])

In [83]:
np.random.random((2, 2))

array([[0.07546891, 0.99513928],
       [0.9514597 , 0.03821244]])

In [85]:
np.random.randint(1, 10)

3

In [99]:
np.random.randint(1, 5, (2, 2))

array([[2, 4],
       [2, 2]])

In [101]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.random.choice(a)

7

In [104]:
##########################  NUMPY String Operations ########################

In [107]:
s1 = 'Vivek is my name'
s2 = '. Hello World'

In [108]:
 np.char.add(s1, s2)

array('Vivek is my name. Hello World', dtype='<U29')

In [109]:
np.char.upper(s1)

array('VIVEK IS MY NAME', dtype='<U16')

In [110]:
np.char.split(s1)

array(list(['Vivek', 'is', 'my', 'name']), dtype=object)

In [114]:
np.char.replace(s1, 'name', 'naam')

array('Vivek is my naam', dtype='<U16')